codecov:
  require_ci_to_pass: true
  branch: main
  max_report_age: false

coverage:
  precision: 2
  round: down
  range: "50...100"
  status:
    patch: false
    project:
      default: false
      applicationstatus:
        target: 50%
        flags:
          - applicationstatus

      releasenotes:
        target: 50%
        flags:
          - releasenotes

ignore:
  - "^/tests/**/*" # ignore test harness code

parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      method: false
      macro: false

comment:
  layout: "diff,flags,tree"
  behavior: default
  require_changes: true

flags:
  applicationstatus:
    paths:
      - apps/application-status
    carryforward: true
  releasenotes:
    paths:
      - apps/release-notes
    carryforward: true